version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: Postgres-db
    restart: always
    environment:
      POSTGRES_DB: fliplearn-db
      POSTGRES_USER: fliplearn-user
      POSTGRES_PASSWORD: fliplearn123
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
